In [ ]:
'''
create sql dataset from hdf5 files directly
   
@author - Farzan Memarian
 this is based on Andrew's id_title_artist.py and Alen's create_song_sql.py
'''
import hdf5_getters
from tqdm import tqdm
import pymysql.cursors
import pandas as pd
import numpy as np
import glob
import csv
import pdb

# establish connection to sql server
connection = pymysql.connect(host='localhost',\
   user='root',db='songs')
cursor = connection.cursor()

# create sql table (only need to do this once)
# sql = '''CREATE TABLE songs (

# songID VARCHAR(50) PRIMARY KEY, 
# artist VARCHAR(400) DEFAULT NULL,
# title VARCHAR(400) DEFAULT NULL,
# danceability REAL,
# duration REAL,
# energy REAL,
# loudness REAL,
# musicalKey INT,
# mode INT,
# tempo REAL,

# INDEX artist (artist)
# );'''
# cursor.execute(sql)
# connection.commit()

glob_path = '/home/frank/1CSEM/1UTCoursesTaken/dataMiningEE380L/termProject/dataset/MillionSongSubset/data/*/*/*/*'
filepaths = glob.glob(glob_path)
for filepath in tqdm(filepaths):
    h5 = hdf5_getters.open_h5_file_read(filepath)
    n = hdf5_getters.get_num_songs(h5)
    # print n
    for row in range(n):
        artist = hdf5_getters.get_artist_name(h5,songidx=row).decode('UTF-8')
        song_id = hdf5_getters.get_song_id(h5,songidx=row).decode('UTF-8')
        title= hdf5_getters.get_title(h5,songidx=row).decode('UTF-8')
        danceability = hdf5_getters.get_danceability(h5,songidx=row)
        duration = hdf5_getters.get_duration(h5,songidx=row)
        energy = hdf5_getters.get_energy(h5,songidx=row)
        loudness = hdf5_getters.get_loudness(h5,songidx=row)
        musicalKey = hdf5_getters.get_key(h5,songidx=row)
        mode = hdf5_getters.get_mode(h5,songidx=row)
        tempo = hdf5_getters.get_tempo(h5,songidx=row)
        artist_mbtags = hdf5_getters.get_artist_mbtags(h5,songidx=row)
        artist_mbtags_count = hdf5_getters.get_artist_mbtags_count(h5,songidx=row)
        tempo = hdf5_getters.get_tempo(h5,songidx=row)
        print(tempo)
        print(artist_mbtags)
        print(artist_mbtags_count)
        # info = [song_id, title, artist]
        # pdb.set_trace()
        # populate sql table with data
        query = "INSERT INTO songs (songID, artist, title, danceability, duration, energy, loudness, musicalKey,\
            mode, tempo) VALUES ('%s', '%s','%s','%s','%s','%s','%s','%s','%s','%s')"\
            % (song_id, artist.replace("'",""), title.replace("'",""), danceability, duration, energy,\
              loudness, musicalKey, mode, tempo)
        cursor.execute(query)
        connection.commit()
    h5.close()

# close sql connection
cursor.close()
connection.close()

  0%|          | 6/10000 [00:00<03:09, 52.63it/s]

84.96
[]
[]
150.04
[b'post-punk' b'uk' b'british' b'new wave' b'english' b'80s' b'goth'
 b'rock and indie' b'70s' b'manchester' b'britannique']
[4 3 3 2 2 2 1 1 1 1 1]
91.964
[]
[]
131.552
[]
[]
192.07
[]
[]
91.005
[b'world']
[1]
100.881
[]
[]
87.507
[]
[]
68.537
[]
[]
122.488
[b'alternative rock' b'rock' b'pop' b'indie rock' b'american'
 b'pop and chart']
[1 1 1 1 1 1]
94.257
[]
[]


  0%|          | 17/10000 [00:00<03:12, 51.74it/s]

110.0
[b'deutschland']
[1]
115.434
[]
[]
87.326
[b'hip hop rnb and dance hall' b'us' b'hiphop']
[1 1 1]
148.071
[b'uk' b'punk' b'england' b'bournemouth' b'anarcho']
[1 1 1 1 1]
167.941
[]
[]
90.811
[]
[]
61.634
[b'conductor']
[1]
121.948
[b'pop' b'pop and chart' b'am\xc3\xa9ricain' b'electronic' b'usa'
 b'american' b'singer' b'tell me' b'chanteur']
[3 1 1 1 1 1 1 1 1]
85.865
[b'german' b'hip hop']
[2 1]
200.289
[]
[]
144.424
[b'uk' b'english' b'british' b'punk' b'england' b'mod'
 b'classic pop and rock']
[2 1 1 1 1 1 1]


  0%|          | 29/10000 [00:00<03:12, 51.89it/s]

194.283
[b'uk' b'british' b'english' b'classic pop and rock' b'production music']
[1 1 1 1 1]
92.499
[]
[]
131.986
[]
[]
85.268
[]
[]
91.568
[]
[]
135.91
[]
[]
109.961
[]
[]
122.976
[]
[]
74.985
[]
[]
137.687
[]
[]
162.133
[b'avant-garde' b'american']
[2 1]


  0%|          | 41/10000 [00:00<03:09, 52.44it/s]

141.975
[b'filk']
[1]
90.05
[]
[]
124.562
[]
[]
137.663
[]
[]
119.271
[]
[]
98.377
[]
[]
77.072
[b'south african']
[1]
95.677
[]
[]
150.575
[]
[]
140.185
[b'black metal' b'portuguese' b'gothic metal' b'metal']
[1 1 1 1]
118.123
[]
[]


  1%|          | 52/10000 [00:01<03:30, 47.23it/s]

167.885
[b'american']
[1]
99.998
[]
[]
113.397
[]
[]
89.607
[b'british' b'punk rock' b'uk' b'london' b'england' b'english'
 b'britannique' b'classic pop and rock' b'rock' b'punk']
[4 3 3 1 1 1 1 1 1 1]
125.653
[b'post-hardcore' b'alternative rock' b'rock']
[1 1 1]
143.764
[b'latin jazz' b'jazz']
[1 1]
185.452
[b'rock and indie']
[1]
127.955
[]
[]
103.832
[b'hip hop rnb and dance hall']
[1]


  1%|          | 64/10000 [00:01<03:18, 50.17it/s]

161.991
[b'uk' b'british' b'english' b'classic pop and rock' b'female singer']
[1 1 1 1 1]
163.136
[]
[]
120.077
[]
[]
88.002
[]
[]
158.244
[b'classic pop and rock']
[1]
188.481
[]
[]
95.787
[]
[]
89.518
[]
[]
105.653
[]
[]
83.469
[]
[]
140.449
[]
[]


  1%|          | 70/10000 [00:01<03:14, 50.93it/s]

110.494
[]
[]
125.717
[]
[]
109.831
[]
[]
114.325
[]
[]
81.53
[b'hip-hop' b'american' b'hip hop rnb and dance hall' b'rapper' b'us'
 b'producer']
[2 1 1 1 1 1]
101.458
[]
[]
123.29
[]
[]
181.239
[]
[]
150.986
[]
[]
88.12
[]
[]
142.991
[]
[]


  1%|          | 82/10000 [00:01<03:09, 52.28it/s]

83.724
[]
[]
115.498
[b'hip-hop' b'turntablism']
[2 1]
96.978
[]
[]
82.005
[b'hip hop rnb and dance hall']
[1]
83.985
[b'folk']
[1]
134.07
[]
[]
93.859
[]
[]
87.714
[]
[]
121.691
[b'rock and indie']
[1]
97.067
[]
[]
134.734
[b'rock and indie' b'united states' b'alternative rock' b'american' b'usa'
 b'heartland rock' b'am\xc3\xa9ricain']
[1 1 1 1 1 1 1]


  1%|          | 94/10000 [00:01<03:10, 51.98it/s]

104.357
[b'rock and indie' b'hip hop']
[1 1]
122.832
[b'american' b'rock and indie']
[1 1]
88.843
[]
[]
83.897
[b'classic pop and rock' b'folk']
[1 1]
120.986
[]
[]
126.941
[]
[]
122.166
[b'folk']
[1]
133.058
[b'french']
[1]
93.162
[]
[]
84.978
[]
[]
130.923
[]
[]
127.369
[b'uk' b'british' b'english' b'rock and indie' b'punk' b'england' b'indie'
 b'post punk' b'alternative']
[2 1 1 1 1 1 1 1 1]


  1%|          | 106/10000 [00:02<03:03, 53.80it/s]

75.064
[b'blues rock']
[1]
84.907
[]
[]
96.043
[]
[]
125.562
[]
[]
70.123
[]
[]
200.617
[]
[]
122.838
[b'hard rock' b'american' b'heavy metal' b'rock' b'metal'
 b'classic pop and rock']
[3 2 1 1 1 1]
83.573
[]
[]
100.82
[b'blues']
[1]
98.563
[]
[]
119.763
[]
[]
92.433
[]
[]


  1%|          | 118/10000 [00:02<03:06, 52.94it/s]

216.557
[]
[]
106.644
[]
[]
117.004
[]
[]
162.356
[]
[]
123.491
[]
[]
63.263
[b'classic pop and rock']
[1]
119.52
[]
[]
130.011
[]
[]
125.45
[]
[]
165.469
[]
[]


  1%|          | 124/10000 [00:02<03:35, 45.81it/s]

157.177
[]
[]
110.056
[b'punk' b'usa' b'classic pop and rock' b'protopunk' b'rock' b'american'
 b'punk rock' b'glam punk']
[1 1 1 1 1 1 1 1]
98.733
[b'french' b'european' b'rock and indie']
[2 1 1]
140.197
[]
[]
141.706
[]
[]
137.686
[b'cantopop' b'cantonese' b'hong kong' b'chinese']
[1 1 1 1]
66.155
[b'hard rock' b'psychedelic rock' b'rock' b'acid rock' b'american'
 b'blues rock' b'classic pop and rock']
[1 1 1 1 1 1 1]
130.039
[b'italian' b'one-hit wonder' b'european']
[2 1 1]
139.905
[b'country']
[1]
47.97
[b'american' b'opera' b'mezzo-soprano']
[1 1 1]


  1%|▏         | 136/10000 [00:02<03:21, 48.89it/s]

134.192
[b'latin' b'pop']
[1 1]
131.639
[b'steal your goals']
[1]
136.981
[]
[]
111.223
[b'belgian' b'european' b'alternative rock' b'dance' b'rock' b'indie rock'
 b'dance and electronica']
[2 1 1 1 1 1 1]
131.986
[]
[]
105.902
[b'alternative rock' b'rock' b'pop' b'indie rock' b'american'
 b'pop and chart']
[1 1 1 1 1 1]
101.241
[]
[]
136.326
[]
[]
42.797
[]
[]
123.797
[b'soundtrack' b'american']
[3 1]
87.467
[]
[]


  1%|▏         | 148/10000 [00:02<03:16, 50.22it/s]

136.478
[]
[]
119.983
[]
[]
132.358
[]
[]
195.995
[]
[]
207.238
[b'hardcore punk' b'california' b'hermosa beach' b'usa' b'rock and indie'
 b'classic hardcore punk' b'california punk' b'classic punk' b'punk']
[2 2 1 1 1 1 1 1 1]
95.264
[b'classic pop and rock']
[1]
206.941
[b'british' b'soft rock' b'jazz' b'rock' b'adult contemporary'
 b'progressive rock' b'english' b'pop' b'uk' b'pop rock'
 b'classic pop and rock']
[2 1 1 1 1 1 1 1 1 1 1]
152.34
[]
[]
113.445
[]
[]
112.911
[]
[]
123.784
[]
[]


  2%|▏         | 160/10000 [00:03<03:09, 51.85it/s]

98.927
[]
[]
94.838
[b'irish' b'rock' b'ireland' b'irlandais' b'classic pop and rock'
 b'\xc3\xa9ire' b'irlande']
[3 3 2 1 1 1 1]
134.028
[]
[]
88.344
[]
[]
160.089
[]
[]
98.442
[]
[]
104.284
[b'country' b'american' b'greatest hits']
[1 1 1]
142.978
[]
[]
121.56
[]
[]
112.486
[b'progressive rock']
[1]
130.201
[b'house' b'trance' b'techno' b'electronic' b'rave' b'british']
[1 1 1 1 1 1]


  2%|▏         | 172/10000 [00:03<03:10, 51.69it/s]

88.644
[]
[]
126.946
[]
[]
77.006
[]
[]
151.184
[b'punk' b'new york' b'usa']
[1 1 1]
101.871
[]
[]
111.682
[]
[]
113.487
[]
[]
89.077
[]
[]
133.193
[b'british' b'soul' b'pop' b'uk' b'english' b'pop and chart' b'r b' b'rnb']
[2 2 2 1 1 1 1 1]
36.624
[]
[]
74.894
[]
[]


  2%|▏         | 184/10000 [00:03<03:19, 49.10it/s]

90.291
[]
[]
73.11
[]
[]
163.567
[]
[]
145.93
[]
[]
99.237
[b'irish folk' b'irish' b'folk']
[1 1 1]
145.971
[b'soundtrack' b'video game' b'english'
 b'easy listening soundtracks and musicals' b'united kingdom'
 b'production music']
[2 1 1 1 1 1]
145.021
[]
[]
16.258
[]
[]
109.721
[b'greek' b'european']
[2 1]
115.029
[]
[]


  2%|▏         | 190/10000 [00:03<03:16, 49.96it/s]

161.804
[b'german']
[1]
185.592
[]
[]
121.852
[]
[]
126.71
[]
[]
142.963
[]
[]
191.548
[]
[]
77.827
[]
[]
163.99
[]
[]
89.672
[]
[]
159.886
[]
[]
81.832
[b'american']
[1]


  2%|▏         | 202/10000 [00:03<03:12, 50.98it/s]

106.821
[b'rock and indie' b'hip hop']
[1 1]
107.983
[]
[]
137.002
[]
[]
160.109
[b'pop rock' b'pop punk' b'pop and chart' b'post-emo' b'emo-pop']
[1 1 1 1 1]
109.08
[]
[]
134.538
[]
[]
92.975
[b'indie' b'pop' b'cantonese' b'hong kong' b'chinese']
[1 1 1 1 1]
132.786
[b'christian rock']
[1]
137.23
[b'jazz and blues']
[1]
114.047
[b'phil spector' b'american' b'pop' b'rock and indie']
[1 1 1 1]
237.466
[b'funk' b'rnb' b'american' b'soul' b'soul and reggae']
[1 1 1 1 1]


  2%|▏         | 214/10000 [00:04<03:04, 52.91it/s]

75.452
[]
[]
138.256
[]
[]
194.691
[]
[]
106.552
[b'jazz and blues']
[1]
150.112
[b'uk' b'british' b'english' b'classic pop and rock']
[1 1 1 1]
116.618
[]
[]
137.296
[]
[]
179.999
[]
[]
119.446
[]
[]
87.982
[b'british' b'english' b'sevenoaks' b'house' b'techno' b'electronica'
 b'electronic' b'ambient techno' b'uk' b'dance and electronica']
[3 1 1 1 1 1 1 1 1 1]
82.98
[]
[]
105.217
[]
[]


  2%|▏         | 226/10000 [00:04<03:01, 53.72it/s]

88.58
[b'uk' b'british' b'english' b'classic pop and rock']
[1 1 1 1]
128.544
[]
[]
103.015
[]
[]
104.035
[]
[]
171.597
[]
[]
151.528
[b'country']
[1]
112.706
[]
[]
120.072
[b'industrial rock' b'norwegian']
[1 1]
148.294
[]
[]
127.597
[b'soul and reggae' b'hip hop']
[1 1]
130.402
[b'spanish' b'pop']
[1 1]


  2%|▏         | 238/10000 [00:04<03:13, 50.54it/s]

122.483
[b'finnish']
[1]
114.595
[b'uk' b'british' b'english' b'rock and indie' b'80s synthpop'
 b'united kingdom']
[1 1 1 1 1 1]
145.999
[b'rock and indie' b'slow pop' b'adam levine' b'united states']
[1 1 1 1]
110.034
[]
[]
124.714
[b'progressive rock' b'uk' b'british' b'english']
[1 1 1 1]
78.437
[]
[]
186.23
[]
[]
101.295
[]
[]
86.09
[]
[]
132.167
[]
[]


  2%|▎         | 250/10000 [00:04<03:07, 51.95it/s]

131.917
[b'classical']
[1]
108.301
[b'hip hop']
[1]
192.297
[b'finnish']
[1]
232.436
[]
[]
152.084
[b'uk' b'electronic' b'english' b'british' b'pop and chart']
[1 1 1 1 1]
165.476
[]
[]
86.958
[b'rock and indie' b'united states' b'alternative rock' b'american' b'usa'
 b'heartland rock' b'am\xc3\xa9ricain']
[1 1 1 1 1 1 1]
125.032
[]
[]
106.549
[]
[]
120.253
[]
[]
92.099
[b'rock and indie']
[1]


  3%|▎         | 256/10000 [00:04<03:06, 52.31it/s]

105.101
[b'country-es']
[1]
187.401
[]
[]
136.749
[b'classic pop and rock']
[1]
157.376
[]
[]
101.306
[b'indie rock' b'american' b'indie pop' b'usa' b'dream pop' b'twee pop'
 b'rock and indie' b'ben gibbard' b'rock' b'am\xc3\xa9ricain']
[4 3 2 1 1 1 1 1 1 1]
164.359
[b'rock' b'pop' b'american' b'classic pop and rock']
[1 1 1 1]
120.944
[]
[]
117.674
[]
[]
130.72
[]
[]
70.296
[b'uk' b'british' b'english' b'rock and indie' b'downtempo' b'electronica'
 b'electronic' b'united kingdom']
[1 1 1 1 1 1 1 1]
150.867
[]
[]


  3%|▎         | 268/10000 [00:05<03:05, 52.40it/s]

160.017
[]
[]
124.996
[b'blues']
[1]
118.834
[]
[]
127.995
[b'house' b'electronic' b'progressive house']
[1 1 1]
130.164
[b'detroit' b'punk' b'michigan' b'usa']
[1 1 1 1]
129.986
[]
[]
97.431
[]
[]
204.304
[b'pop and chart' b'pop' b'will i am' b'fergie' b'united states']
[1 1 1 1 1]
94.771
[]
[]
141.961
[]
[]
149.765
[b'chinese']
[1]


  3%|▎         | 280/10000 [00:05<03:01, 53.42it/s]

106.145
[]
[]
106.002
[b'punk' b'new jersey' b'usa' b'new brunswick']
[1 1 1 1]
149.423
[b'greek' b'electronic' b'instrumental' b'soundtrack' b'new age'
 b'soundtrack composer' b'experimental' b'progressive new age' b'ambient'
 b'composer' b'classical' b'progressive rock' b'rock' b'film score'
 b'easy listening soundtracks and musicals']
[5 4 3 3 3 2 1 1 1 1 1 1 1 1 1]
160.267
[]
[]
40.384
[b'country']
[2]
116.239
[b'rock and indie']
[1]
88.947
[]
[]
90.787
[]
[]
219.131
[]
[]
167.831
[]
[]
87.844
[b'german' b'german hip-hop' b'hip-hop' b'rap']
[2 1 1 1]


  3%|▎         | 292/10000 [00:05<03:15, 49.66it/s]

140.823
[]
[]
56.703
[]
[]
121.923
[]
[]
100.532
[]
[]
93.301
[b'american']
[1]
138.504
[]
[]
134.929
[b'roots rock' b'rock' b'american' b'pop' b'heartland rock']
[1 1 1 1 1]
111.643
[b'greek' b'european']
[2 1]
130.023
[]
[]
126.1
[b'canadian' b'country rock' b'rock' b'folk']
[2 1 1 1]


  3%|▎         | 304/10000 [00:05<03:09, 51.05it/s]

130.231
[]
[]
148.684
[b'reggae' b'jamaican' b'soul and reggae' b'bob-marley']
[1 1 1 1]
118.099
[b'hip hop rnb and dance hall']
[1]
124.969
[]
[]
102.117
[]
[]
241.818
[b'folk' b'soft rock' b'acoustic' b'rock' b'american' b'surf'
 b'pop and chart']
[2 1 1 1 1 1 1]
111.997
[b'dance and electronica']
[1]
88.796
[]
[]
153.974
[b'folk']
[1]
145.185
[]
[]
86.805
[b'american' b'folk']
[1 1]


  3%|▎         | 310/10000 [00:06<03:06, 51.92it/s]

124.995
[]
[]
111.629
[b'rock' b'british' b'alternative rock' b'art rock' b'uk' b'electronic'
 b'english' b'britannique' b'melancholic' b'parlophone' b'britpop'
 b'thom yorke' b'rock and indie' b'oxford']
[5 4 2 2 2 2 2 1 1 1 1 1 1 1]
105.539
[b'folk' b'celtic' b'irish folk' b'irish' b'breton']
[2 1 1 1 1]
85.816
[b'german']
[1]
90.645
[]
[]
159.134
[]
[]
87.61
[]
[]
175.954
[b'country']
[2]
123.998
[b'hip hop rnb and dance hall']
[1]
95.953
[]
[]
80.472
[b'punk' b'california' b'usa' b'poway']
[1 1 1 1]


  3%|▎         | 322/10000 [00:06<03:04, 52.55it/s]

157.087
[]
[]
139.115
[b'black metal' b'death metal' b'polish' b'blackened death metal' b'metal']
[2 2 1 1 1]
193.919
[b'hip hop rnb and dance hall']
[1]
93.033
[]
[]
127.999
[b'pop' b'pop and chart' b'am\xc3\xa9ricain' b'electronic' b'usa'
 b'american' b'singer' b'tell me' b'chanteur']
[3 1 1 1 1 1 1 1 1]
87.468
[b'soul and reggae']
[1]
107.022
[b'hip hop']
[1]
199.792
[]
[]
186.12
[]
[]
131.487
[]
[]
159.673
[b'producer' b'rock' b'songwriter' b'pop']
[1 1 1 1]


  3%|▎         | 334/10000 [00:06<03:01, 53.24it/s]

107.411
[]
[]
161.737
[b'dancehall' b'dub' b'hip hop rnb and dance hall']
[1 1 1]
80.16
[]
[]
104.272
[]
[]
100.266
[]
[]
97.065
[]
[]
95.929
[b'whistle register' b'rnb' b'pop' b'american' b'pop and chart']
[1 1 1 1 1]
130.004
[]
[]
127.463
[]
[]
147.91
[]
[]
86.686
[]
[]


  3%|▎         | 346/10000 [00:06<03:12, 50.04it/s]

169.898
[b'chinese' b'pop' b'hong kong' b'cantonese' b'mandarin']
[3 2 1 1 1]
96.616
[]
[]
149.527
[b'classic pop and rock' b'rock']
[1 1]
121.687
[]
[]
95.543
[b'soundtrack' b'classical' b'contemporary classical' b'american'
 b'easy listening soundtracks and musicals']
[2 1 1 1 1]
96.002
[]
[]
70.183
[]
[]
103.022
[]
[]
141.705
[b'country pop' b'country']
[1 1]
124.291
[b'country' b'rock' b'american' b'pop' b'classic pop and rock']
[1 1 1 1 1]


  4%|▎         | 358/10000 [00:06<03:05, 51.98it/s]

100.003
[]
[]
155.611
[]
[]
114.929
[b'black metal' b'death metal' b'polish' b'blackened death metal' b'metal']
[2 2 1 1 1]
89.013
[]
[]
141.257
[]
[]
201.494
[]
[]
100.451
[]
[]
60.15
[]
[]
102.922
[]
[]
114.528
[]
[]
109.965
[b'french']
[1]


  4%|▎         | 364/10000 [00:07<03:05, 51.92it/s]

85.599
[b'classical' b'french' b'european']
[2 2 1]
234.361
[]
[]
189.288
[]
[]
97.594
[b'rock and indie' b'hip hop']
[1 1]
196.196
[b'uk' b'punk' b'england' b'bournemouth' b'anarcho']
[1 1 1 1 1]
185.498
[b'hip-hop' b'turntablism']
[2 1]
106.446
[]
[]
95.425
[b'uk' b'4ad' b'british' b'english']
[1 1 1 1]
129.983
[]
[]
160.039
[]
[]
132.174
[b'chinese']
[1]


  4%|▍         | 376/10000 [00:07<03:15, 49.30it/s]

72.188
[]
[]
114.346
[]
[]
124.006
[]
[]
57.639
[b'soul and reggae']
[1]
179.976
[]
[]
101.971
[b'american' b'folk']
[1 1]
174.468
[b'punk' b'usa']
[1 1]
97.955
[b'classic pop and rock']
[1]
146.826
[b'irish' b'rock' b'ireland' b'irlandais' b'classic pop and rock'
 b'\xc3\xa9ire' b'irlande']
[3 3 2 1 1 1 1]
126.992
[]
[]


  4%|▍         | 388/10000 [00:07<03:06, 51.58it/s]

128.013
[]
[]
106.515
[]
[]
116.764
[b'american' b'rnb' b'soul' b'pop']
[2 1 1 1]
79.091
[b'classic pop and rock' b'folk']
[1 1]
147.602
[b'folk' b'soft rock' b'acoustic' b'rock' b'american' b'surf'
 b'pop and chart']
[2 1 1 1 1 1 1]
86.005
[]
[]
148.341
[]
[]
101.311
[]
[]
60.308
[]
[]
160.05
[]
[]
93.507
[]
[]


  4%|▍         | 400/10000 [00:07<03:05, 51.80it/s]

96.261
[]
[]
110.123
[]
[]
162.016
[]
[]
142.968
[]
[]
128.48
[]
[]
89.481
[]
[]
149.234
[]
[]
123.033
[b'metal' b'death metal' b'american' b'industrial metal' b'phonetic phail'
 b'progressive metal' b'gratuitous heavy metal umlaut' b'thrash metal']
[2 2 2 1 1 1 1 1]
174.395
[]
[]
95.192
[b'alternative hip-hop' b'progressive hip-hop' b'american' b'hip-hop'
 b'hip hop rnb and dance hall']
[1 1 1 1 1]
142.212
[b'dubstep' b'dark ambient' b'producers']
[3 1 1]


  4%|▍         | 412/10000 [00:08<03:03, 52.17it/s]

86.104
[b'american' b'blues rock' b'acid rock' b'guitarist' b'psychedelic rock'
 b'classic rock' b'psychadelic' b'classic pop and rock' b'60s'
 b'united states' b'psychedelic' b'hard rock' b'rock' b'guitar god']
[3 3 2 2 2 1 1 1 1 1 1 1 1 1]
89.095
[]
[]
103.177
[b'bossa nova' b'rock and indie']
[1 1]
127.749
[]
[]
114.638
[]
[]
101.139
[b'rock' b'blues rock']
[1 1]
122.015
[]
[]
109.857
[b'seen live' b'rock and indie' b'alternative' b'australia']
[2 1 1 1]
184.15
[b'rock and indie' b'hip hop']
[1 1]
178.471
[]
[]
156.107
[b'czech']
[1]


  4%|▍         | 418/10000 [00:08<03:02, 52.37it/s]

99.352
[]
[]
104.013
[b'wu-tang' b'us' b'hiphop']
[1 1 1]
164.049
[b'rock and indie' b'slow pop' b'adam levine' b'united states']
[1 1 1 1]
143.854
[]
[]
182.393
[]
[]
89.984
[]
[]
48.385
[]
[]
117.665
[]
[]
127.814
[b'greek']
[2]
131.991
[]
[]
91.691
[b'folk']
[1]


  4%|▍         | 430/10000 [00:08<03:00, 52.91it/s]

146.64
[]
[]
182.672
[b'swing' b'bossa nova' b'latin jazz' b'brazilian' b'jazz' b'american'
 b'brazilian jazz']
[1 1 1 1 1 1 1]
94.653
[]
[]
97.979
[b'alternative rock' b'columbus' b'usa' b'ohio']
[1 1 1 1]
96.474
[b'soundtrack composer' b'french' b'production music']
[1 1 1]
98.063
[]
[]
107.675
[]
[]
116.045
[b'salsa' b'latin']
[1 1]
93.068
[]
[]
84.186
[b'jazz and blues']
[1]
108.013
[]
[]


  4%|▍         | 442/10000 [00:08<02:58, 53.45it/s]

106.187
[]
[]
126.019
[]
[]
90.719
[b'rock' b'folk rock' b'country rock' b'american' b'classic pop and rock']
[2 1 1 1 1]
140.496
[]
[]
54.192
[]
[]
114.805
[b'country' b'western' b'american']
[1 1 1]
130.422
[]
[]
120.406
[]
[]
222.916
[]
[]
113.447
[b'jazz and blues']
[1]
108.941
[]
[]


  5%|▍         | 454/10000 [00:08<03:09, 50.30it/s]

134.021
[]
[]
137.465
[b'production music']
[1]
123.438
[b'soft rock' b'popular' b'rock' b'american'
 b'easy listening soundtracks and musicals']
[1 1 1 1 1]
143.699
[b'alternative rock' b'southern rock' b'hard rock' b'rock' b'post-grunge']
[1 1 1 1 1]
60.276
[b'hip-hop' b'american' b'hip hop rnb and dance hall' b'rapper' b'us'
 b'producer']
[2 1 1 1 1 1]
87.006
[]
[]
171.693
[b'punk rock' b'rock' b'american' b'pop punk' b'punk' b'usa'
 b'christian punk' b'alt punk']
[2 1 1 1 1 1 1 1]
163.921
[]
[]
154.244
[b'british' b'rock' b'electronica' b'electronic' b'arena rock'
 b'progressive rock' b'uk' b'english' b'classic pop and rock' b'70s' b'80s'
 b'pop rock']
[2 2 1 1 1 1 1 1 1 1 1 1]
141.004
[b'uk' b'british' b'english' b'classic pop and rock' b'punk' b'london'
 b'rock' b'england' b'punk rock']
[2 2 1 1 1 1 1 1 1]


  5%|▍         | 466/10000 [00:09<03:04, 51.71it/s]

81.689
[]
[]
161.071
[b'usa' b'american' b'punk rock' b'punk' b'hardcore punk' b'epitaph'
 b'atlantic' b'classic hardcore punk' b'melodic hardcore' b'classic punk'
 b'am\xc3\xa9ricain' b'rock and indie' b'california punk' b'california']
[2 2 2 2 2 1 1 1 1 1 1 1 1 1]
98.388
[]
[]
139.469
[]
[]
116.815
[b'heavy metal' b'am\xc3\xa9ricain' b'usa' b'american' b'metal']
[1 1 1 1 1]
89.607
[]
[]
170.732
[]
[]
95.385
[b'dance and electronica']
[1]
125.228
[b'hip hop rnb and dance hall' b'dangerous']
[1 1]
176.121
[]
[]
114.072
[b'german' b'hip hop']
[2 1]


  5%|▍         | 472/10000 [00:09<03:09, 50.40it/s]

168.121
[]
[]
111.67
[]
[]
131.642
[b'rock and indie']
[1]
99.701
[b'blues']
[1]
196.022
[b'folk' b'indie folk' b'usa' b'american' b'am\xc3\xa9ricain']
[2 1 1 1 1]
196.429
[b'espa\xc3\xb1ol' b'argentina']
[1 1]
119.057
[]
[]
118.454
[]
[]
175.781
[]
[]
123.401
[b'folk']
[1]


  5%|▍         | 483/10000 [00:09<03:21, 47.17it/s]

125.802
[]
[]
107.371
[]
[]
95.866
[b'classic pop and rock']
[1]
95.103
[b'pop and chart']
[1]
93.292
[b'folk']
[1]
122.015
[]
[]
119.901
[]
[]
63.087
[]
[]
230.041
[]
[]
137.953
[b'british' b'english' b'techno' b'dance-punk' b'alternative dance' b'uk'
 b'rock' b'electronic' b'electronica' b'alternative rock']
[2 2 1 1 1 1 1 1 1 1]


  5%|▍         | 493/10000 [00:09<03:17, 48.22it/s]

154.995
[]
[]
137.937
[b'hard rock' b'grunge' b'alternative rock' b'rock' b'american']
[1 1 1 1 1]
145.941
[b'norwegian']
[1]
123.755
[b'hip hop rnb and dance hall']
[1]
61.305
[]
[]
134.804
[]
[]
125.163
[b'production music']
[1]
108.895
[]
[]
147.0
[]
[]
111.28
[b'mandarin' b'cantonese' b'hong kong' b'chinese']
[1 1 1 1]


  5%|▌         | 503/10000 [00:09<03:20, 47.26it/s]

140.026
[]
[]
122.148
[]
[]
58.47
[]
[]
90.438
[b'norwegian' b'black metal' b'melodic black metal'
 b'symphonic black metal' b'metal']
[4 3 2 2 2]
91.099
[b'hip hop rnb and dance hall' b'rnb' b'pop']
[1 1 1]
115.584
[]
[]
93.373
[]
[]
167.677
[]
[]
109.474
[b'american' b'rock and indie']
[1 1]
137.113
[]
[]


  5%|▌         | 515/10000 [00:10<03:10, 49.87it/s]

121.884
[b'whistle register' b'rnb' b'pop' b'american' b'pop and chart']
[1 1 1 1 1]
118.241
[]
[]
200.114
[b'hip hop rnb and dance hall' b'rapper' b'hip-hop']
[1 1 1]
102.151
[]
[]
145.333
[]
[]
117.495
[b'soul and reggae']
[1]
102.006
[]
[]
131.525
[]
[]
170.61
[b'danish']
[1]
132.159
[]
[]
137.614
[]
[]


  5%|▌         | 527/10000 [00:10<03:01, 52.14it/s]

116.298
[]
[]
150.59
[]
[]
91.302
[]
[]
128.646
[b'uk' b'british' b'english' b'rock and indie' b'80s synthpop'
 b'united kingdom']
[1 1 1 1 1 1]
146.976
[]
[]
151.741
[]
[]
151.123
[b'uk' b'british' b'english' b'classic pop and rock']
[1 1 1 1]
102.785
[b'classic pop and rock' b'blues']
[1 1]
101.947
[]
[]
202.358
[]
[]
115.304
[]
[]


  5%|▌         | 533/10000 [00:10<03:06, 50.68it/s]

131.909
[]
[]
136.32
[b'british' b'soft rock' b'jazz' b'rock' b'adult contemporary'
 b'progressive rock' b'english' b'pop' b'uk' b'pop rock'
 b'classic pop and rock']
[2 1 1 1 1 1 1 1 1 1 1]
198.855
[b'world']
[1]
115.616
[]
[]
141.872
[]
[]
87.327
[]
[]
133.3
[b'pop rock' b'alternative rock' b'rock' b'american'
 b'classic pop and rock' b'united states']
[1 1 1 1 1 1]
130.867
[b'alternative metal' b'rock' b'american' b'metal' b'experimental rock'
 b'crossover' b'alternative rock' b'rock and indie' b'political'
 b'new metal' b'nu metal']
[3 2 1 1 1 1 1 1 1 1 1]
161.176
[b'ska' b'latin' b'argentina']
[1 1 1]


  5%|▌         | 545/10000 [00:10<03:11, 49.39it/s]

74.697
[]
[]
96.683
[b'folk' b'irish' b'celtic']
[2 1 1]
138.207
[]
[]
143.061
[]
[]
72.882
[b'chinese' b'mandarin' b'hong kong']
[1 1 1]
121.983
[b'rock and indie']
[1]
167.832
[b'german' b'jazz' b'european']
[3 1 1]
128.444
[b'salsa' b'latin']
[1 1]
130.103
[]
[]
87.679
[b'hard rock' b'protopunk' b'punk rock' b'garage rock' b'shock rock'
 b'rock' b'glam rock' b'american' b'classic pop and rock' b'usa']
[1 1 1 1 1 1 1 1 1 1]
119.991
[]
[]


  6%|▌         | 557/10000 [00:10<03:03, 51.54it/s]

158.429
[b'american' b'folk']
[1 1]
95.234
[]
[]
75.017
[]
[]
161.191
[]
[]
168.0
[b'us' b'hiphop' b'hip hop']
[1 1 1]
119.947
[]
[]
118.656
[]
[]
120.232
[b'taiwanese' b'mandarin' b'chinese']
[1 1 1]
152.343
[b'german' b'german hip-hop' b'hip-hop' b'rap']
[2 1 1 1]
66.932
[]
[]
77.806
[]
[]
90.998
[b'x']
[1]


  6%|▌         | 569/10000 [00:11<02:57, 53.03it/s]

105.027
[]
[]
171.944
[b'rock and indie' b'lincoln park' b'rock' b'usa' b'michigan']
[1 1 1 1 1]
66.41
[b'alternative rock' b'am\xc3\xa9ricain' b'american' b'usa'
 b'rock and indie' b'dream pop' b'hard rock' b'grunge' b'90s'
 b'progressive rock' b'ambient' b'alternative' b'rock' b'shoegaze'
 b'indie rock' b'united states']
[2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
105.142
[]
[]
39.899
[]
[]
94.0
[]
[]
84.977
[]
[]
147.97
[b'\xe9\xa6\x99\xe6\xb8\xaf\xe6\xad\x8c\xe6\x89\x8b' b'hong kong artist'
 b'hong kong' b'chinese']
[2 2 1 1]
129.956
[]
[]
95.389
[b'american']
[1]
97.036
[]
[]


  6%|▌         | 581/10000 [00:11<03:04, 50.92it/s]

78.902
[]
[]
114.169
[]
[]
94.987
[b'barbadian' b'pop and chart' b'barbade' b'barbadien' b'pop' b'dance-pop'
 b'contemporary r b' b'rnb' b'barbados']
[3 1 1 1 1 1 1 1 1]
125.217
[]
[]
156.616
[]
[]
175.945
[]
[]
64.798
[b'european' b'austrian']
[1 1]
124.508
[]
[]
107.601
[b'delta blues' b'blues' b'electric blues']
[1 1 1]
97.519
[]
[]


  6%|▌         | 587/10000 [00:11<03:11, 49.22it/s]

90.463
[b'south american' b'rock en espa\xc3\xb1ol' b'rock' b'soundtrack'
 b'argentinian' b'easy listening soundtracks and musicals' b'argentina'
 b'espa\xc3\xb1ol' b'bajofondo']
[1 1 1 1 1 1 1 1 1]
92.761
[]
[]
105.026
[b'singer' b'dancer' b'indian']
[1 1 1]
101.998
[]
[]
113.838
[]
[]
162.006
[]
[]
106.361
[]
[]
84.818
[]
[]
90.59
[]
[]
131.568
[b'classic pop and rock']
[1]


  6%|▌         | 599/10000 [00:11<03:02, 51.53it/s]

92.32
[b'blues']
[1]
118.198
[]
[]
138.021
[]
[]
134.033
[b'german' b'pop']
[1 1]
203.944
[b'uk' b'british' b'english' b'classic pop and rock' b'punk' b'london'
 b'rock' b'england' b'punk rock']
[2 2 1 1 1 1 1 1 1]
139.315
[]
[]
110.361
[]
[]
170.029
[]
[]
118.776
[b'ska' b'latin' b'argentina']
[1 1 1]
154.099
[]
[]
91.988
[b'hip hop rnb and dance hall']
[1]


  6%|▌         | 611/10000 [00:11<03:07, 50.20it/s]

91.479
[]
[]
140.052
[]
[]
187.958
[]
[]
162.019
[b'stoner metal']
[1]
133.125
[]
[]
195.317
[b'rock and indie']
[1]
105.882
[]
[]
125.604
[]
[]
140.003
[]
[]
88.49
[b'italian' b'european']
[1 1]


  6%|▌         | 623/10000 [00:12<03:06, 50.30it/s]

90.854
[]
[]
150.003
[]
[]
82.124
[b'rock and indie']
[1]
65.941
[]
[]
98.011
[]
[]
103.02
[]
[]
74.481
[]
[]
158.569
[]
[]
189.294
[b'hip hop rnb and dance hall']
[1]
110.924
[]
[]
53.713
[]
[]


  6%|▋         | 629/10000 [00:12<03:02, 51.31it/s]

35.604
[]
[]
87.192
[]
[]
122.13
[]
[]
129.953
[]
[]
123.69
[]
[]
160.589
[]
[]
85.538
[]
[]
169.654
[b'heavy metal' b'hard rock' b'rock' b'american' b'metal'
 b'instrumental rock' b'archives']
[1 1 1 1 1 1 1]
219.569
[]
[]
117.362
[b'pop' b'american' b'rnb' b'rock' b'dance-pop' b'new jack swing' b'soul'
 b'disco' b'cool' b'classic pop and rock' b'michael-jackson'
 b'united states' b'singer' b'parolier' b'compositeur' b'chanteur'
 b'lyricist' b'composer' b'usa' b'contemporary rnb']
[4 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
124.894
[]
[]


  6%|▋         | 641/10000 [00:12<03:03, 51.09it/s]

100.44
[b'hip hop rnb and dance hall' b'hip hop']
[1 1]
69.114
[b'uk' b'british' b'english' b'rock and indie' b'80s synthpop'
 b'united kingdom']
[1 1 1 1 1 1]
156.021
[]
[]
110.828
[]
[]
0.0
[b'jazz and blues']
[1]
86.991
[b'dance and electronica' b'drum and bass']
[1 1]
98.987
[]
[]
127.969
[b'rock' b'christian']
[1 1]
180.009
[]
[]
79.606
[b'folk']
[1]


  7%|▋         | 652/10000 [00:12<03:13, 48.39it/s]

108.634
[]
[]
121.739
[]
[]
131.564
[b'uk' b'british' b'english' b'classic pop and rock' b'production music']
[1 1 1 1 1]
154.038
[b'protopunk' b'folk-rock' b'noise rock' b'experimental rock'
 b'gothic rock' b'art rock' b'rock' b'glam rock' b'american'
 b'classic pop and rock']
[1 1 1 1 1 1 1 1 1 1]
102.649
[]
[]
117.858
[]
[]
168.027
[]
[]
180.253
[]
[]
127.985
[]
[]
140.017
[]
[]


  7%|▋         | 664/10000 [00:13<03:04, 50.60it/s]

110.411
[]
[]
132.636
[]
[]
121.733
[]
[]
141.223
[b'hard rock' b'rock' b'glam metal' b'metal' b'american' b'pop and chart']
[1 1 1 1 1 1]
157.696
[]
[]
72.777
[]
[]
153.833
[b'alternative rock' b'rock' b'am\xc3\xa9ricain' b'usa' b'jangle pop'
 b'rock and indie' b'pop rock' b'georgia' b'athens' b'american'
 b'college rock']
[4 2 1 1 1 1 1 1 1 1 1]
86.612
[]
[]
99.752
[]
[]
92.974
[]
[]
147.932
[]
[]


  7%|▋         | 676/10000 [00:13<02:57, 52.39it/s]

65.019
[]
[]
69.573
[b'rock and indie' b'hip hop']
[1 1]
148.264
[]
[]
100.869
[]
[]
112.897
[]
[]
96.598
[]
[]
95.863
[b'german']
[2]
98.071
[b'soul and reggae']
[1]
98.8
[]
[]
40.027
[]
[]
193.426
[b'french']
[1]


  7%|▋         | 682/10000 [00:13<02:56, 52.75it/s]

191.063
[b'american' b'punk' b'usa' b'punk rock' b'am\xc3\xa9ricain'
 b'hardcore punk' b'ska punk' b'los angeles' b'skate punk' b'rock']
[3 2 2 1 1 1 1 1 1 1]
137.976
[]
[]
108.829
[]
[]
149.984
[]
[]
130.28
[]
[]
124.798
[]
[]
166.03
[b'alternative metal' b'american' b'metal' b'experimental rock'
 b'rock and indie' b'alternative rock' b'nu metal' b'am\xc3\xa9ricain'
 b'usa' b'new metal' b'rock']
[2 2 1 1 1 1 1 1 1 1 1]
104.53
[]
[]
152.986
[b'classical']
[1]
229.221
[]
[]
146.422
[]
[]


  7%|▋         | 694/10000 [00:13<02:55, 52.91it/s]

86.778
[]
[]
124.998
[]
[]
178.427
[b'punk' b'usa' b'connecticut' b'new haven']
[1 1 1 1]
130.052
[]
[]
170.94
[]
[]
147.057
[]
[]
144.017
[b'industrial metal' b'american' b'metal' b'alternative metal']
[2 2 1 1]
103.995
[]
[]
71.478
[]
[]
125.093
[b'punk' b'france']
[1 1]
103.142
[b'punk' b'california' b'usa' b'poway']
[1 1 1 1]


  7%|▋         | 706/10000 [00:13<03:08, 49.37it/s]

143.676
[]
[]
61.618
[]
[]
157.932
[]
[]
133.787
[]
[]
98.246
[]
[]
90.021
[b'thrash metal' b'metal' b'metalcore' b'american' b'hardcore'
 b'groove metal']
[2 2 2 1 1 1]
94.499
[b'rock and indie' b'hip hop']
[1 1]
119.336
[]
[]
120.047
[]
[]


  7%|▋         | 717/10000 [00:14<03:04, 50.20it/s]

128.004
[]
[]
84.017
[b'cantonese' b'hong kong' b'pop' b'chinese']
[1 1 1 1]
155.091
[b'trance' b'christian']
[1 1]
145.105
[]
[]
182.589
[]
[]
109.509
[]
[]
96.112
[b'south african']
[1]
119.526
[]
[]
124.985
[b'finnish']
[1]
134.48
[b'finnish']
[1]
81.674
[b'german']
[1]


  7%|▋         | 729/10000 [00:14<02:57, 52.19it/s]

124.513
[b'uk' b'british' b'english' b'world' b'folk']
[1 1 1 1 1]
153.802
[]
[]
201.459
[]
[]
100.922
[b'classic pop and rock']
[1]
105.291
[]
[]
164.33
[]
[]
166.002
[]
[]
133.812
[]
[]
152.785
[b'indie rock' b'american' b'rock' b'rock and indie' b'2000s'
 b'garage rock' b'alternative rock']
[2 2 1 1 1 1 1]
85.776
[b'birmingham' b'uk' b'british' b'english' b'classic pop and rock']
[1 1 1 1 1]
162.025
[b'rock' b'pop and chart' b'canada' b'post-grunge' b'pop rock'
 b'alternative rock' b'punk']
[2 1 1 1 1 1 1]


  7%|▋         | 735/10000 [00:14<02:56, 52.48it/s]

162.618
[b'jamaican']
[1]
117.001
[]
[]
137.754
[b'classic pop and rock']
[1]
89.658
[b'rap' b'hip hop rnb and dance hall']
[1 1]
133.838
[]
[]
127.387
[]
[]
83.413
[]
[]
139.768
[]
[]
148.975
[]
[]
88.471
[b'classic pop and rock' b'rock']
[1 1]
137.741
[]
[]


  7%|▋         | 747/10000 [00:14<02:53, 53.37it/s]

109.059
[]
[]
140.084
[]
[]
113.031
[]
[]
85.155
[b'ambient']
[1]
71.609
[b'spanish' b'european']
[1 1]
149.629
[]
[]
89.957
[]
[]
115.014
[b'jungle' b'uk' b'english' b'drum and bass' b'british']
[1 1 1 1 1]
88.341
[b'greek' b'electronic' b'instrumental' b'soundtrack' b'new age'
 b'soundtrack composer' b'experimental' b'progressive new age' b'ambient'
 b'composer' b'classical' b'progressive rock' b'rock' b'film score'
 b'easy listening soundtracks and musicals']
[5 4 3 3 3 2 1 1 1 1 1 1 1 1 1]
124.393
[]
[]
153.251
[]
[]


  8%|▊         | 759/10000 [00:14<02:52, 53.57it/s]

91.008
[]
[]
136.786
[]
[]
115.671
[b'finnish']
[1]
155.906
[]
[]
126.428
[]
[]
119.291
[]
[]
182.456
[]
[]
150.958
[]
[]
100.455
[]
[]
208.567
[b'folk']
[1]
107.597
[]
[]


  8%|▊         | 771/10000 [00:15<02:52, 53.64it/s]

169.797
[]
[]
131.612
[b'french' b'eurovision' b'y\xc3\xa9-y\xc3\xa9' b'pop']
[3 1 1 1]
140.042
[b'german' b'electronic' b'synthpop' b'krautrock' b'classic pop and rock'
 b'electro' b'european' b'd\xc3\xbcsseldorf' b'techno' b'rock'
 b'industrial']
[5 3 3 2 1 1 1 1 1 1 1]
105.837
[]
[]
139.009
[b'rock and indie']
[1]
94.853
[]
[]
96.037
[]
[]
109.062
[b'hip hop']
[1]
144.026
[]
[]
104.821
[b'pop' b'pop and chart' b'am\xc3\xa9ricain' b'electronic' b'usa'
 b'american' b'singer' b'tell me' b'chanteur']
[3 1 1 1 1 1 1 1 1]
81.302
[]
[]


  8%|▊         | 783/10000 [00:15<02:51, 53.81it/s]

84.462
[]
[]
183.048
[b'rock and indie']
[1]
86.71
[b'brazil']
[1]
122.99
[]
[]
102.399
[b'dancehall' b'dub' b'hip hop rnb and dance hall']
[1 1 1]
120.423
[]
[]
162.38
[]
[]
80.521
[b'hip hop rnb and dance hall']
[1]
155.982
[]
[]
120.172
[b'irish folk' b'irish' b'folk']
[1 1 1]
65.901
[]
[]


  8%|▊         | 795/10000 [00:15<02:56, 52.12it/s]

161.739
[b'hip hop rnb and dance hall']
[1]
86.164
[]
[]
144.002
[]
[]
110.706
[]
[]
164.972
[]
[]
108.153
[]
[]
161.986
[b'taiwanese' b'hong kong' b'mandarin' b'chinese' b'production music']
[2 1 1 1 1]
139.186
[b'german']
[1]
94.31
[b'german' b'hip hop']
[2 1]
155.08
[]
[]
109.079
[]
[]


  8%|▊         | 801/10000 [00:15<02:56, 52.15it/s]

147.97
[]
[]
195.462
[]
[]
136.915
[]
[]
87.872
[b'punk' b'new york' b'usa']
[1 1 1]
126.855
[]
[]
70.608
[]
[]
88.02
[]
[]
100.229
[]
[]
93.976
[]
[]
103.579
[]
[]
135.151
[b'spanish' b'pop']
[1 1]


  8%|▊         | 813/10000 [00:15<02:56, 51.97it/s]

63.972
[]
[]
97.683
[b'country']
[1]
88.861
[]
[]
122.341
[b'british' b'english' b'rock' b'pop' b'classic pop and rock'
 b'my sweet lord' b'folk' b'uk' b'united kingdom']
[2 1 1 1 1 1 1 1 1]
88.889
[b'stoner rock' b'american' b'hard rock' b'rock' b'rock and indie'
 b'alternative rock']
[3 2 2 2 1 1]
132.43
[b'latvian']
[1]
170.047
[]
[]
91.493
[b'brazilian' b'south american' b'brazilian classics player']
[2 1 1]
128.007
[]
[]
137.804
[]
[]
124.019
[b'mandarin' b'cantonese' b'hong kong' b'chinese']
[1 1 1 1]


  8%|▊         | 825/10000 [00:16<02:58, 51.34it/s]

100.552
[]
[]
176.014
[]
[]
106.671
[b'phil spector' b'american' b'pop' b'rock and indie']
[1 1 1 1]
99.933
[b'folk']
[1]
103.801
[]
[]
104.0
[]
[]
258.677
[b'german' b'comedian']
[2 1]
120.148
[b'french' b'british' b'english']
[1 1 1]
95.752
[b'performance name' b'american' b'hip-hop' b'hip hop rnb and dance hall']
[1 1 1 1]
169.822
[]
[]
210.253
[b'uk' b'scottish' b'british' b'pop and chart']
[1 1 1 1]


  8%|▊         | 837/10000 [00:16<02:56, 51.81it/s]

118.02
[]
[]
133.891
[]
[]
183.94
[]
[]
160.067
[]
[]
123.044
[]
[]
154.246
[b'classic pop and rock']
[1]
63.641
[]
[]
146.01
[]
[]
81.626
[]
[]
141.257
[b'folk' b'soft rock' b'acoustic' b'rock' b'american' b'surf'
 b'pop and chart']
[2 1 1 1 1 1 1]
200.249
[]
[]


  8%|▊         | 849/10000 [00:16<02:53, 52.72it/s]

82.799
[]
[]
101.918
[b'ragtime' b'country blues' b'delta blues' b'chicago blues' b'american'
 b'piedmont blues']
[1 1 1 1 1 1]
102.155
[]
[]
166.409
[b'mathcore' b'grindcore' b'sucky' b'experimental' b'american' b'metal']
[1 1 1 1 1 1]
139.286
[b'french']
[1]
102.739
[b'american' b'sludge metal' b'metal' b'doom metal' b'stoner metal']
[1 1 1 1 1]
93.77
[]
[]
173.945
[b'pop and chart']
[1]
126.83
[b'classic pop and rock' b'classic rock']
[1 1]
75.487
[]
[]
131.915
[]
[]


  9%|▊         | 861/10000 [00:16<02:51, 53.22it/s]

88.313
[b'erroll garner' b'folk']
[1 1]
85.325
[b'pop and chart']
[1]
90.217
[]
[]
135.426
[]
[]
94.996
[b'folk metal' b'swiss' b'melodic death metal' b'celtic metal'
 b'gaulish lyrics' b'metal']
[1 1 1 1 1 1]
103.027
[]
[]
94.15
[b'rock and indie']
[1]
135.314
[b'rock and indie']
[1]
169.672
[]
[]
169.951
[b'hip hop rnb and dance hall' b'hip hop']
[1 1]
73.581
[]
[]


  9%|▊         | 867/10000 [00:16<02:52, 53.00it/s]

165.142
[]
[]
85.744
[b'birmingham' b'uk' b'british' b'english' b'warp' b'classic pop and rock']
[1 1 1 1 1 1]
89.965
[]
[]
147.599
[b'british' b'uk' b'rock' b'new wave' b'english' b'classic pop and rock'
 b'post-punk' b'england' b'alternative']
[2 2 1 1 1 1 1 1 1]
195.824
[b'classic pop and rock']
[1]
161.961
[]
[]
110.875
[b'alternative rock' b'funk rock' b'funk' b'rock' b'crossover' b'10s'
 b'usa' b'00s' b'90s' b'80s' b'metal' b'rap' b'funk metal' b'american'
 b'pop and chart']
[3 3 2 2 1 1 1 1 1 1 1 1 1 1 1]
113.096
[]
[]
99.219
[b'european' b'austrian']
[1 1]
150.573
[]
[]


  9%|▉         | 879/10000 [00:17<03:09, 48.20it/s]

74.55
[]
[]
73.411
[b'mpb']
[1]
129.237
[b'soundtrack' b'classical' b'contemporary classical' b'american'
 b'easy listening soundtracks and musicals']
[2 1 1 1 1]
143.85
[b'reggae' b'rasta' b'jamaican']
[3 1 1]
142.893
[]
[]
234.334
[b'folk']
[2]
156.202
[]
[]
93.773
[b'classic pop and rock']
[1]
114.546
[]
[]


  9%|▉         | 890/10000 [00:17<03:05, 48.98it/s]

138.876
[]
[]
100.017
[]
[]
171.743
[]
[]
109.993
[]
[]
97.536
[]
[]
160.67
[]
[]
120.381
[]
[]
125.1
[]
[]
143.267
[]
[]
128.407
[b'british' b'dance pop' b'blue-eyed soul' b'rock' b'rhythm and blues'
 b'pop' b'uk' b'english' b'pop rock' b'classic pop and rock']
[2 1 1 1 1 1 1 1 1 1]
71.952
[b'american' b'folk']
[1 1]


  9%|▉         | 902/10000 [00:17<03:01, 50.19it/s]

0.0
[]
[]
89.21
[]
[]
164.946
[b'hip hop rnb and dance hall']
[1]
130.683
[b'horror punk' b'american']
[1 1]
209.956
[]
[]
177.551
[b'uk' b'punk' b'england' b'manchester' b'english' b'classic pop and rock'
 b'british']
[2 1 1 1 1 1 1]
124.693
[]
[]
177.972
[]
[]
100.329
[b'blues' b'american']
[1 1]
123.006
[]
[]
136.021
[b'mandarin' b'cantonese' b'cantopop' b'mandopop' b'hong kong' b'chinese']
[1 1 1 1 1 1]


  9%|▉         | 908/10000 [00:17<02:59, 50.70it/s]

117.696
[]
[]
158.016
[]
[]
150.407
[b'french']
[1]
44.816
[b'progressive rock' b'british' b'progressive metal' b'metal' b'uk'
 b'psychedelic rock' b'english' b'classic pop and rock' b'folk' b'new prog'
 b'rock']
[4 2 2 1 1 1 1 1 1 1 1]
0.0
[]
[]
71.077
[b'uk' b'british' b'english' b'classic pop and rock']
[1 1 1 1]
160.006
[]
[]
106.681
[]
[]
96.179
[b'trip rock' b'british' b'electronica' b'rock' b'electronic' b'hip-hop'
 b'trip-hop' b'parlophone' b'uk' b'english' b'rock and indie' b'fictional'
 b'producteur' b'producer' b'alternative rock' b'united kingdom'
 b'alternative hip-hop']
[2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
85.506
[]
[]
106.407
[]
[]


  9%|▉         | 919/10000 [00:17<03:09, 47.95it/s]

197.011
[b'british' b'dance' b'electronic' b'uk' b'10s' b'00s' b'english' b'90s'
 b'house' b'uk garage' b'dance and electronica']
[4 3 2 2 1 1 1 1 1 1 1]
135.733
[b'hip hop rnb and dance hall']
[1]
118.167
[]
[]
150.087
[]
[]
131.85
[]
[]
122.511
[]
[]
128.45
[b'british' b'soul' b'pop' b'uk' b'english' b'pop and chart' b'r b' b'rnb']
[2 2 2 1 1 1 1 1]
134.056
[b'wales' b'glam metal' b'british' b'metal']
[1 1 1 1]
119.831
[b'german' b'soundtrack' b'german composer' b'european' b'composer'
 b'film composer']
[3 2 1 1 1 1]
169.333
[b'french' b'toulouse']
[1 1]


  9%|▉         | 929/10000 [00:18<03:08, 48.05it/s]

135.344
[]
[]
133.18
[]
[]
121.983
[b'dance and electronica']
[1]
99.993
[b'fran\xc3\xa7ais' b'french' b'france' b'pop' b'francophone' b'guitarist'
 b'parolier' b'guitariste' b'compositeur' b'composer' b'chanteur'
 b'lyricist' b'singer']
[1 1 1 1 1 1 1 1 1 1 1 1 1]
127.937
[b'hip hop rnb and dance hall']
[1]
227.247
[]
[]
93.017
[]
[]
165.552
[b'ska']
[1]
71.707
[b'rock and indie' b'metal']
[1 1]
157.67
[]
[]
110.889
[]
[]


  9%|▉         | 941/10000 [00:18<03:03, 49.35it/s]

112.522
[]
[]
106.019
[]
[]
40.258
[]
[]
144.412
[]
[]
98.428
[b'hard rock' b'instrumental' b'rock']
[1 1 1]
122.831
[b'rock' b'british' b'alternative rock' b'art rock' b'uk' b'electronic'
 b'english' b'britannique' b'melancholic' b'parlophone' b'britpop'
 b'thom yorke' b'rock and indie' b'oxford']
[5 4 2 2 2 2 2 1 1 1 1 1 1 1]
91.965
[]
[]
223.617
[b'british' b'dance pop' b'blue-eyed soul' b'rock' b'rhythm and blues'
 b'pop' b'uk' b'english' b'pop rock' b'classic pop and rock']
[2 1 1 1 1 1 1 1 1 1]
41.634
[]
[]
133.297
[b'bosnia and herzegovina' b'avantgarde']
[1 1]


 10%|▉         | 951/10000 [00:18<03:20, 45.15it/s]

95.471
[]
[]
94.648
[]
[]
121.996
[]
[]
106.932
[]
[]
90.92
[b'alternative rock' b'rock' b'art punk' b'dance-punk' b'noise rock'
 b'experimental rock' b'rock and indie']
[1 1 1 1 1 1 1]
125.309
[]
[]
195.208
[b'hip hop rnb and dance hall']
[1]
151.8
[b'alternative rock' b'southern rock' b'hard rock' b'rock' b'post-grunge']
[1 1 1 1 1]
103.003
[b'gospel']
[1]
143.239
[b'hard rock' b'rock' b'blues rock' b'british' b'english'
 b'classic pop and rock' b'uk' b'classic rock' b'folk' b'am\xc3\xa9ricain'
 b'usa' b'american' b'folk rock' b'heavy metal' b'metal']
[6 5 3 3 1 1 1 1 1 1 1 1 1 1 1]


 10%|▉         | 962/10000 [00:18<03:06, 48.58it/s]

155.659
[b'production music']
[1]
93.633
[b'production music']
[1]
88.627
[]
[]
142.666
[b'hip hop rnb and dance hall']
[1]
104.346
[]
[]
84.015
[]
[]
103.546
[]
[]
161.033
[]
[]
91.988
[b'desi' b'electro']
[1 1]
165.621
[b'uk' b'punk' b'oi' b'london' b'england' b'classic pop and rock']
[1 1 1 1 1 1]
132.946
[b'rock and indie' b'electroclash' b'rock' b'australian' b'electronic'
 b'electro']
[1 1 1 1 1 1]


 10%|▉         | 974/10000 [00:19<03:02, 49.57it/s]

140.407
[b'french']
[2]
79.076
[]
[]
111.942
[]
[]
85.06
[]
[]
128.998
[]
[]
56.216
[]
[]
117.142
[]
[]
187.176
[b'punk' b'hardcore punk' b'pop-punk' b'california' b'lomita' b'usa']
[2 1 1 1 1 1]
126.184
[b'german' b'jazz' b'european']
[3 1 1]
70.784
[]
[]


 10%|▉         | 984/10000 [00:19<03:11, 46.96it/s]

122.414
[]
[]
94.705
[b'british' b'soft rock' b'jazz' b'rock' b'adult contemporary'
 b'progressive rock' b'english' b'pop' b'uk' b'pop rock'
 b'classic pop and rock']
[2 1 1 1 1 1 1 1 1 1 1]
180.073
[]
[]
97.79
[]
[]
64.958
[]
[]
110.462
[]
[]
66.807
[]
[]
140.354
[]
[]
127.601
[b'british']
[1]
161.853
[b'rock and indie' b'hip hop']
[1 1]


 10%|▉         | 996/10000 [00:19<03:03, 49.11it/s]

159.9
[]
[]
92.755
[]
[]
156.581
[]
[]
85.401
[b'blues rock']
[1]
117.58
[]
[]
172.371
[]
[]
88.464
[]
[]
84.159
[]
[]
149.492
[b'rock' b'british' b'alternative rock' b'art rock' b'uk' b'electronic'
 b'english' b'britannique' b'melancholic' b'parlophone' b'britpop'
 b'thom yorke' b'rock and indie' b'oxford']
[5 4 2 2 2 2 2 1 1 1 1 1 1 1]
146.008
[]
[]
191.406
[b'pop and chart' b'the queen' b'janet-jackson']
[1 1 1]


 10%|█         | 1001/10000 [00:19<03:14, 46.38it/s]

179.001
[]
[]
131.502
[]
[]
85.0
[b'turkish']
[2]
143.29
[]
[]
99.381
[]
[]
232.709
[b'heavy metal' b'hard rock' b'rock' b'metal' b'american' b'blues rock'
 b'classic pop and rock']
[1 1 1 1 1 1 1]
116.083
[]
[]
78.498
[]
[]
151.357
[]
[]


 10%|█         | 1012/10000 [00:19<03:11, 46.92it/s]

153.939
[]
[]
120.227
[]
[]
166.09
[b'punk' b'thrash metal' b'crossover thrash' b'metal' b'hardcore punk'
 b'usa' b'thrash' b'rapcore' b'american' b'funk metal' b'alternative metal']
[2 2 2 2 2 1 1 1 1 1 1]
146.051
[]
[]
154.113
[]
[]
173.974
[]
[]
80.975
[]
[]
109.896
[]
[]
89.919
[]
[]
129.293
[]
[]
128.319
[b'dance and electronica']
[1]


 10%|█         | 1024/10000 [00:20<02:59, 50.05it/s]

183.566
[b'american' b'rock' b'big band' b'pop' b'rock and roll'
 b'easy listening soundtracks and musicals' b'folk']
[2 1 1 1 1 1 1]
262.828
[]
[]
121.797
[]
[]
180.02
[]
[]
100.209
[]
[]
151.164
[]
[]
101.854
[]
[]
56.184
[b'country' b'folk']
[1 1]
89.818
[b'los angeles' b'american']
[1 1]
133.325
[b'rock and indie']
[1]
104.115
[b'american' b'alternative rock' b'power pop' b'rock' b'geek rock' b'usa'
 b'nerd rock' b'rock and indie' b'am\xc3\xa9ricain' b'weezer']
[3 3 3 2 2 1 1 1 1 1]


 10%|█         | 1036/10000 [00:20<02:56, 50.79it/s]

135.909
[]
[]
182.721
[]
[]
90.356
[]
[]
85.981
[]
[]
147.003
[]
[]
120.02
[]
[]
75.467
[]
[]
96.384
[]
[]
140.119
[]
[]
151.973
[]
[]
139.91
[]
[]


 10%|█         | 1047/10000 [00:20<03:12, 46.43it/s]

96.123
[]
[]
138.033
[b'chinese']
[1]
125.971
[]
[]
123.829
[b'uk' b'british' b'english' b'dance and electronica']
[1 1 1 1]
140.252
[]
[]
106.927
[b'dance and electronica']
[1]
88.304
[]
[]
134.531
[b'latvian']
[1]
123.003
[]
[]


 11%|█         | 1053/10000 [00:20<03:06, 47.89it/s]

164.041
[b'german' b'hip hop']
[2 1]
99.077
[b'dance and electronica']
[1]
146.93
[]
[]
92.331
[]
[]
105.958
[]
[]
119.423
[]
[]
89.995
[]
[]
120.0
[]
[]
154.164
[]
[]
118.926
[]
[]
81.649
[]
[]


 11%|█         | 1065/10000 [00:20<02:58, 50.05it/s]

128.018
[b'rock' b'christian']
[1 1]
143.748
[b'alternative rock' b'rock' b'art punk' b'dance-punk' b'noise rock'
 b'experimental rock' b'rock and indie']
[1 1 1 1 1 1 1]
117.535
[b'classic pop and rock']
[1]
107.965
[b'ndw' b'german']
[1 1]
153.713
[b'alternative metal' b'american' b'metal' b'experimental rock'
 b'rock and indie' b'alternative rock' b'nu metal' b'am\xc3\xa9ricain'
 b'usa' b'new metal' b'rock']
[2 2 1 1 1 1 1 1 1 1 1]
172.909
[b'rock' b'blues rock' b'british' b'english' b'classic pop and rock'
 b'blues']
[2 2 1 1 1 1]
85.811
[]
[]
106.01
[b'french']
[1]
133.96
[]
[]
112.181
[]
[]
99.654
[]
[]


 11%|█         | 1077/10000 [00:21<02:53, 51.44it/s]

159.164
[]
[]
112.222
[]
[]
131.348
[b'punk' b'usa' b'classic pop and rock' b'protopunk' b'rock' b'american'
 b'punk rock' b'glam punk']
[1 1 1 1 1 1 1 1]
111.756
[]
[]
83.066
[]
[]
148.077
[b'folk']
[1]
100.441
[]
[]
149.972
[]
[]
87.735
[]
[]
103.562
[b'jazz and blues']
[1]
174.49
[]
[]


 11%|█         | 1089/10000 [00:21<02:50, 52.39it/s]

90.098
[b'rock and indie']
[1]
97.969
[b'post-hardcore' b'southern rock' b'rock' b'american']
[1 1 1 1]
85.979
[]
[]
99.863
[]
[]
188.018
[b'electronic' b'big beat']
[2 1]
172.054
[]
[]
118.027
[]
[]
107.329
[b'salsa' b'latin']
[1 1]
109.402
[b'uk' b'australian' b'british' b'english']
[1 1 1 1]
103.886
[]
[]
126.57
[b'60s' b'70s' b'blues' b'trio' b'british' b'english' b'80s'
 b'classic pop and rock']
[1 1 1 1 1 1 1 1]


 11%|█         | 1101/10000 [00:21<02:49, 52.55it/s]

97.865
[]
[]
156.957
[]
[]
80.162
[]
[]
87.351
[b'bristol' b'rock and indie' b'drum and bass' b'british']
[1 1 1 1]
136.217
[]
[]
100.078
[]
[]
128.518
[b'black metal']
[1]
134.539
[]
[]
113.557
[]
[]
130.229
[b'pop and chart' b'the queen' b'janet-jackson']
[1 1 1]
170.192
[]
[]


 11%|█         | 1113/10000 [00:21<02:47, 53.03it/s]

89.3
[]
[]
105.434
[]
[]
186.511
[]
[]
166.864
[b'usa' b'american' b'punk rock' b'punk' b'hardcore punk' b'epitaph'
 b'atlantic' b'classic hardcore punk' b'melodic hardcore' b'classic punk'
 b'am\xc3\xa9ricain' b'rock and indie' b'california punk' b'california']
[2 2 2 2 2 1 1 1 1 1 1 1 1 1]
166.531
[b'country']
[1]
80.672
[]
[]
146.606
[]
[]
151.199
[]
[]
90.18
[b'hip-hop' b'detroit hip-hop' b'american' b'pop and chart' b'us' b'hiphop'
 b'8 mile' b'midwest hip-hop' b'hip hop']
[2 1 1 1 1 1 1 1 1]
120.234
[]
[]
79.86
[b'italian' b'soundtrack']
[1 1]


 11%|█         | 1119/10000 [00:21<02:47, 52.99it/s]

104.989
[]
[]
186.393
[b'hip hop']
[1]
142.82
[b'rock and indie' b'hip hop']
[1 1]
124.517
[b'ska punk' b'pop rock' b'rnb' b'rock' b'pop rap' b'dance-pop' b'pop'
 b'new wave' b'american' b'pop and chart' b'no doubt' b'united states']
[1 1 1 1 1 1 1 1 1 1 1 1]
87.525
[b'hip hop rnb and dance hall']
[1]
163.881
[b'hip-hop' b'rock and indie' b'hip hop' b'rap']
[1 1 1 1]
103.916
[]
[]
134.009
[b'rock and indie']
[1]
114.216
[]
[]
98.507
[b'pop and chart' b'emo' b'united states']
[1 1 1]
103.829
[]
[]


 11%|█▏        | 1131/10000 [00:22<02:49, 52.42it/s]

116.024
[]
[]
201.21
[]
[]
111.81
[b'hip hop rnb and dance hall']
[1]
110.3
[]
[]
109.44
[]
[]
196.681
[]
[]
112.032
[]
[]
125.693
[]
[]
100.811
[]
[]
126.615
[b'italian' b'european']
[1 1]
113.485
[b'rnb' b'neo soul' b'soul' b'hip hop rnb and dance hall' b'united states'
 b'singer' b'american' b'pianist']
[2 1 1 1 1 1 1 1]


 11%|█▏        | 1143/10000 [00:22<02:46, 53.24it/s]

190.333
[b'british' b'punk rock' b'uk' b'london' b'england' b'english'
 b'britannique' b'classic pop and rock' b'rock' b'punk']
[4 3 3 1 1 1 1 1 1 1]
90.049
[]
[]
144.463
[]
[]
92.471
[]
[]
122.701
[]
[]
139.423
[b'greek']
[2]
111.661
[]
[]
85.515
[]
[]
165.904
[]
[]
97.103
[]
[]
129.988
[]
[]


 12%|█▏        | 1155/10000 [00:22<02:47, 52.67it/s]

173.828
[]
[]
120.444
[]
[]
72.677
[]
[]
94.393
[]
[]
72.211
[]
[]
121.847
[]
[]
192.239
[]
[]
116.279
[]
[]
98.072
[]
[]
119.981
[b'progressive rock' b'uk' b'british' b'english']
[1 1 1 1]
93.382
[]
[]


 12%|█▏        | 1167/10000 [00:22<02:52, 51.07it/s]

126.113
[]
[]
160.26
[b'indie rock' b'british' b'alternative rock' b'art rock' b'rock'
 b'rock and indie' b'post-punk revival' b'uk' b'united kingdom'
 b'britannique']
[2 2 1 1 1 1 1 1 1 1]
120.103
[b'electronic' b'canadian']
[1 1]
126.202
[b'bobby valentin']
[1]
110.058
[]
[]
76.354
[]
[]
114.276
[]
[]
135.021
[]
[]
91.97
[]
[]
163.959
[]
[]


 12%|█▏        | 1173/10000 [00:23<02:56, 49.88it/s]

139.706
[]
[]
81.24
[]
[]
124.595
[]
[]
126.948
[]
[]
124.013
[b'swedish' b'alternative rock' b'indie pop' b'rock' b'european'
 b'rock and indie']
[2 1 1 1 1 1]
208.167
[]
[]
129.393
[]
[]
122.267
[b'new wave' b'english' b'uk' b'synthpop' b'classic pop and rock'
 b'electronic' b'british']
[2 2 1 1 1 1 1]
109.974
[b'greek']
[1]
180.854
[]
[]


 12%|█▏        | 1184/10000 [00:23<02:56, 49.96it/s]

91.087
[b'operatic pop' b'gospel' b'classical' b'easy listening' b'american'
 b'vocal' b'pop' b'easy listening soundtracks and musicals']
[1 1 1 1 1 1 1 1]
84.606
[]
[]
35.351
[]
[]
113.41
[]
[]
64.996
[]
[]
88.011
[b'rock and indie']
[1]
124.915
[b'alternative rock' b'funk rock' b'funk' b'rock' b'crossover' b'10s'
 b'usa' b'00s' b'90s' b'80s' b'metal' b'rap' b'funk metal' b'american'
 b'pop and chart']
[3 3 2 2 1 1 1 1 1 1 1 1 1 1 1]
109.522
[b'hip hop rnb and dance hall' b'rnb' b'pop']
[1 1 1]
95.075
[]
[]
116.338
[b'finnish' b'humppa']
[2 1]
72.357
[]
[]


 12%|█▏        | 1196/10000 [00:23<02:51, 51.31it/s]

89.912
[]
[]
106.936
[]
[]
125.787
[]
[]
178.825
[]
[]
181.002
[b'betulio medina']
[1]
155.979
[b'greek']
[1]
80.945
[]
[]
177.963
[]
[]
98.988
[b'country' b'rock roll' b'rock' b'honky tonk' b'nashville sound'
 b'american' b'pop' b'rock and indie']
[1 1 1 1 1 1 1 1]
109.994
[]
[]
94.709
[]
[]


 12%|█▏        | 1202/10000 [00:23<02:50, 51.65it/s]